"""Tests for generate_report tool and core/reporting.py.

Uses synthetic AnalysisRun objects — does NOT use the real NIR file.
"""
from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from chemometrics_contracts import (
    AnalysisResult,
    AnalysisRun,
    ArtifactReference,
    GenerateReportRequest,
    InterpretationSummary,
    RunMetadata,
    ValidationSummary,
    ValidationWarning,
)

from chemometrics_mcp.core.reporting import (
    _build_next_steps,
    build_agent_readable_summary,
    build_markdown_report,
)
from chemometrics_mcp.tools import generate_report


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_run_metadata(run_id: str = "run-test-abc123") -> RunMetadata:
    return RunMetadata(
        run_id=run_id,
        tool_name="run_analysis",
        dataset_id="test_dataset",
        status="completed",
        created_at="2026-01-01T00:00:00+00:00",
        parameters={"n_samples": 100, "n_features": 50},
    )


def _make_analysis_run(
    *,
    run_id: str = "run-test-abc123",
    include_failed: bool = False,
    include_warnings: bool = False,
    include_artifacts: bool = False,
    empty_results: bool = False,
) -> AnalysisRun:
    if empty_results:
        results: tuple = ()
    else:
        results = (
            AnalysisResult(
                task_name="classification",
                model_name="SVM",
                preprocessing=("snv", "savgol"),
                metrics={"accuracy": 0.92, "f1": 0.91},
            ),
            AnalysisResult(
                task_name="classification",
                model_name="PCA",
                preprocessing=("msc",),
                metrics={"accuracy": 0.85, "f1": 0.84},
            ),
        )

    failed_models = ("RandomForest",) if include_failed else ()
    warnings_list = (
        ValidationWarning(
            code="W001",
            message="Small sample size detected.",
            severity="warning",
        ),
    ) if include_warnings else ()
    artifacts = (
        ArtifactReference(
            kind="metrics_json",
            uri="runs/run-test-abc123/artifacts/metrics.json",
            label="Metrics",
        ),
    ) if include_artifacts else ()

    return AnalysisRun(
        run_metadata=_make_run_metadata(run_id),
        results=results,
        failed_models=failed_models,
        warnings=warnings_list,
        artifacts=artifacts,
    )


def _make_validation_summary(passed: bool = True) -> ValidationSummary:
    return ValidationSummary(
        passed=passed,
        checks={"no_leakage": True, "sufficient_samples": False},
        warnings=(
            ValidationWarning(
                code="V001",
                message="Insufficient samples for robust cross-validation.",
                severity="warning",
            ),
        ),
    )


def _make_interpretation_summary() -> InterpretationSummary:
    return InterpretationSummary(
        summary="SVM shows strong discriminative power in the 1000-1200 nm region.",
        important_features=(1100, 1150, 1200),
        model_comparisons=["SVM outperforms PCA on held-out test set."],
    )


# ---------------------------------------------------------------------------
# Core reporting tests
# ---------------------------------------------------------------------------

class TestBuildMarkdownReport(unittest.TestCase):

    def test_contains_title(self):
        run = _make_analysis_run()
        md = build_markdown_report(run)
        self.assertIn("# Chemometrics Analysis Report", md)

    def test_contains_human_review_checklist(self):
        run = _make_analysis_run()
        md = build_markdown_report(run)
        self.assertIn("## Human Review Checklist", md)

    def test_contains_model_names(self):
        run = _make_analysis_run()
        md = build_markdown_report(run)
        self.assertIn("SVM", md)
        self.assertIn("PCA", md)

    def test_contains_run_id(self):
        run = _make_analysis_run(run_id="run-test-xyz999")
        md = build_markdown_report(run)
        self.assertIn("run-test-xyz999", md)

    def test_contains_footer(self):
        run = _make_analysis_run()
        md = build_markdown_report(run)
        self.assertIn(
            "*Report generated by agentic-chemometrician. All conclusions require human review.*",
            md,
        )

    def test_failed_models_section_present_when_nonempty(self):
        run = _make_analysis_run(include_failed=True)
        md = build_markdown_report(run)
        self.assertIn("RandomForest", md)
        self.assertIn("Failed Models", md)

    def test_failed_models_section_absent_when_empty(self):
        run = _make_analysis_run(include_failed=False)
        md = build_markdown_report(run)
        self.assertNotIn("Failed Models", md)

    def test_validation_section_present_when_provided(self):
        run = _make_analysis_run()
        vs = _make_validation_summary(passed=True)
        md = build_markdown_report(run, validation_summary=vs)
        self.assertIn("## Validation", md)
        self.assertIn("PASSED", md)

    def test_validation_section_absent_when_not_provided(self):
        run = _make_analysis_run()
        md = build_markdown_report(run)
        self.assertNotIn("## Validation", md)

    def test_interpretation_section_present_when_provided(self):
        run = _make_analysis_run()
        interp = _make_interpretation_summary()
        md = build_markdown_report(run, interpretation=interp)
        self.assertIn("## Interpretation", md)
        self.assertIn("SVM shows strong discriminative power", md)

    def test_interpretation_section_absent_when_not_provided(self):
        run = _make_analysis_run()
        md = build_markdown_report(run)
        self.assertNotIn("## Interpretation", md)

    def test_empty_results_produces_valid_report(self):
        run = _make_analysis_run(empty_results=True)
        md = build_markdown_report(run)
        self.assertIn("# Chemometrics Analysis Report", md)
        self.assertIn("Human Review Checklist", md)
        # No crash; report still contains key sections
        self.assertIsInstance(md, str)
        self.assertGreater(len(md), 0)

    def test_preprocessing_comparison_section_present_with_multiple_methods(self):
        run = AnalysisRun(
            run_metadata=_make_run_metadata(),
            results=(
                AnalysisResult(
                    task_name="classification",
                    model_name="SVM",
                    preprocessing=("snv",),
                    metrics={"accuracy": 0.92, "f1": 0.91},
                ),
                AnalysisResult(
                    task_name="classification",
                    model_name="SVM",
                    preprocessing=("msc",),
                    metrics={"accuracy": 0.88, "f1": 0.87},
                ),
            ),
        )
        md = build_markdown_report(run)
        self.assertIn("## Preprocessing Comparison", md)
        self.assertIn("snv", md)
        self.assertIn("msc", md)

    def test_preprocessing_comparison_section_absent_with_single_method(self):
        run = AnalysisRun(
            run_metadata=_make_run_metadata(),
            results=(
                AnalysisResult(
                    task_name="classification",
                    model_name="SVM",
                    preprocessing=("snv",),
                    metrics={"accuracy": 0.92, "f1": 0.91},
                ),
                AnalysisResult(
                    task_name="classification",
                    model_name="RF",
                    preprocessing=("snv",),
                    metrics={"accuracy": 0.85, "f1": 0.84},
                ),
            ),
        )
        md = build_markdown_report(run)
        self.assertNotIn("## Preprocessing Comparison", md)


# ---------------------------------------------------------------------------
# Agent-readable summary tests
# ---------------------------------------------------------------------------

class TestBuildAgentReadableSummary(unittest.TestCase):

    def test_returns_dict_with_all_required_keys(self):
        run = _make_analysis_run()
        summary = build_agent_readable_summary(run)
        required_keys = {
            "run_id",
            "n_results",
            "failed_models",
            "n_warnings",
            "validation_passed",
            "best_accuracy",
            "models_run",
            "approval_required",
        }
        self.assertEqual(required_keys, set(summary.keys()))

    def test_approval_required_is_always_true(self):
        run = _make_analysis_run()
        summary = build_agent_readable_summary(run)
        self.assertTrue(summary["approval_required"])

    def test_best_accuracy_is_highest_across_results(self):
        run = _make_analysis_run()
        summary = build_agent_readable_summary(run)
        # SVM has accuracy 0.92, PCA has 0.85 — best should be 0.92
        self.assertAlmostEqual(summary["best_accuracy"], 0.92)

    def test_n_results_matches_result_count(self):
        run = _make_analysis_run()
        summary = build_agent_readable_summary(run)
        self.assertEqual(summary["n_results"], 2)

    def test_best_accuracy_none_when_no_accuracy_metric(self):
        run = AnalysisRun(
            run_metadata=_make_run_metadata(),
            results=(
                AnalysisResult(
                    task_name="regression",
                    model_name="PLSRegression",
                    metrics={"rmse": 0.05, "r2": 0.98},
                ),
            ),
        )
        summary = build_agent_readable_summary(run)
        self.assertIsNone(summary["best_accuracy"])

    def test_validation_passed_reflects_summary(self):
        run = _make_analysis_run()
        vs = _make_validation_summary(passed=False)
        summary = build_agent_readable_summary(run, validation_summary=vs)
        self.assertFalse(summary["validation_passed"])

    def test_validation_passed_none_when_not_provided(self):
        run = _make_analysis_run()
        summary = build_agent_readable_summary(run)
        self.assertIsNone(summary["validation_passed"])

    def test_run_id_from_metadata(self):
        run = _make_analysis_run(run_id="run-custom-id")
        summary = build_agent_readable_summary(run)
        self.assertEqual(summary["run_id"], "run-custom-id")

    def test_models_run_list(self):
        run = _make_analysis_run()
        summary = build_agent_readable_summary(run)
        self.assertIn("SVM", summary["models_run"])
        self.assertIn("PCA", summary["models_run"])


# ---------------------------------------------------------------------------
# Tool boundary tests
# ---------------------------------------------------------------------------

class TestGenerateReportTool(unittest.TestCase):

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.runs_root = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def _make_request(self, **kwargs) -> GenerateReportRequest:
        run = _make_analysis_run(**kwargs)
        return GenerateReportRequest(analysis_run=run)

    def test_returns_ok_true_for_valid_run(self):
        request = self._make_request()
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)

    def test_report_md_artifact_created(self):
        request = self._make_request()
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        md_path = Path(response.payload.primary_report.uri)
        self.assertTrue(md_path.exists(), f"report.md not found at {md_path}")

    def test_report_summary_json_artifact_created(self):
        request = self._make_request()
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        # Find the JSON artifact
        json_ref = next(
            (a for a in response.payload.artifacts if a.kind == "report_json"),
            None,
        )
        self.assertIsNotNone(json_ref, "No report_json artifact found")
        json_path = Path(json_ref.uri)
        self.assertTrue(json_path.exists(), f"report_summary.json not found at {json_path}")

    def test_primary_report_has_kind_report_markdown(self):
        request = self._make_request()
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        self.assertEqual(response.payload.primary_report.kind, "report_markdown")

    def test_human_readable_summary_is_nonempty(self):
        request = self._make_request()
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        self.assertIsNotNone(response.payload.human_readable_summary)
        self.assertGreater(len(response.payload.human_readable_summary), 0)

    def test_human_readable_summary_max_500_chars(self):
        request = self._make_request()
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        self.assertLessEqual(len(response.payload.human_readable_summary), 500)

    def test_agent_readable_summary_is_valid_json(self):
        request = self._make_request()
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        summary_str = response.payload.agent_readable_summary
        self.assertIsNotNone(summary_str)
        parsed = json.loads(summary_str)
        self.assertIn("approval_required", parsed)
        self.assertTrue(parsed["approval_required"])

    def test_report_title_is_set(self):
        request = self._make_request()
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        self.assertEqual(response.payload.report_title, "Chemometrics Analysis Report")

    def test_warnings_combined_from_run_and_validation(self):
        run = _make_analysis_run(include_warnings=True)
        vs = _make_validation_summary()
        request = GenerateReportRequest(analysis_run=run, validation_summary=vs)
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        # run has 1 warning, validation_summary has 1 warning
        self.assertEqual(len(response.payload.warnings), 2)

    def test_empty_results_still_ok(self):
        request = self._make_request(empty_results=True)
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)

    def test_reuses_run_id_from_analysis_run(self):
        run = _make_analysis_run(run_id="run-reuse-me")
        request = GenerateReportRequest(analysis_run=run)
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        # The artifact URI should contain the run_id
        self.assertIn("run-reuse-me", response.payload.primary_report.uri)

    def test_no_run_metadata_generates_new_run_id(self):
        run = AnalysisRun(
            run_metadata=None,
            results=(
                AnalysisResult(
                    task_name="classification",
                    model_name="SVM",
                    metrics={"accuracy": 0.9},
                ),
            ),
        )
        request = GenerateReportRequest(analysis_run=run)
        response = generate_report.run(request, runs_root=self.runs_root)
        self.assertTrue(response.ok)
        self.assertIsNotNone(response.payload.primary_report)


class TestBuildNextSteps(unittest.TestCase):

    def test_validation_warnings_appear_in_next_steps(self):
        run = _make_analysis_run()
        vs = _make_validation_summary()
        steps = _build_next_steps(run, vs, None)
        self.assertTrue(
            any("Insufficient samples" in s for s in steps),
            f"Expected validation warning in steps, got: {steps}",
        )

    def test_clean_run_produces_review_step(self):
        run = _make_analysis_run()
        vs = ValidationSummary(
            passed=True,
            checks={"split_stability": True},
            warnings=(),
        )
        steps = _build_next_steps(run, vs, None)
        self.assertIn("Results are suitable for expert review and interpretation", steps)

    def test_failed_models_produce_fallback_recommendations(self):
        run = _make_analysis_run(include_failed=True)
        steps = _build_next_steps(run, None, None)
        self.assertTrue(
            any("random_forest" in s and "RandomForest" in s for s in steps),
            f"Expected fallback recommendation for RandomForest, got: {steps}",
        )

    def test_low_metrics_produce_improvement_suggestion(self):
        run = AnalysisRun(
            run_metadata=_make_run_metadata(),
            results=(
                AnalysisResult(
                    task_name="classification",
                    model_name="SVM",
                    preprocessing=("snv",),
                    metrics={"accuracy": 0.55},
                ),
            ),
        )
        vs = ValidationSummary(
            passed=True,
            checks={"split_stability": True},
            warnings=(),
        )
        steps = _build_next_steps(run, vs, None)
        self.assertTrue(
            any("preprocessing or feature selection" in s for s in steps),
            f"Expected low-metric suggestion, got: {steps}",
        )

    def test_low_r2_produces_improvement_suggestion(self):
        run = AnalysisRun(
            run_metadata=_make_run_metadata(),
            results=(
                AnalysisResult(
                    task_name="regression",
                    model_name="PLSR",
                    preprocessing=("snv",),
                    metrics={"r2": 0.3},
                ),
            ),
        )
        vs = ValidationSummary(
            passed=True,
            checks={"split_stability": True},
            warnings=(),
        )
        steps = _build_next_steps(run, vs, None)
        self.assertTrue(
            any("preprocessing or feature selection" in s for s in steps),
            f"Expected low-r2 suggestion, got: {steps}",
        )

    def test_single_preprocessing_suggests_comparison(self):
        run = AnalysisRun(
            run_metadata=_make_run_metadata(),
            results=(
                AnalysisResult(
                    task_name="classification",
                    model_name="SVM",
                    preprocessing=("snv",),
                    metrics={"accuracy": 0.92},
                ),
            ),
        )
        vs = ValidationSummary(
            passed=True,
            checks={"split_stability": True},
            warnings=(),
        )
        steps = _build_next_steps(run, vs, None)
        self.assertTrue(
            any("Compare preprocessing methods" in s for s in steps),
            f"Expected preprocessing comparison suggestion, got: {steps}",
        )

    def test_missing_split_stability_suggests_analysis(self):
        run = _make_analysis_run()
        vs = ValidationSummary(
            passed=True,
            checks={},
            warnings=(),
        )
        steps = _build_next_steps(run, vs, None)
        self.assertTrue(
            any("split instability" in s.lower() for s in steps),
            f"Expected split instability suggestion, got: {steps}",
        )

    def test_none_validation_summary_handled_gracefully(self):
        run = _make_analysis_run()
        steps = _build_next_steps(run, None, None)
        self.assertIsInstance(steps, list)
        self.assertGreater(len(steps), 0)


class TestNextStepsInReport(unittest.TestCase):

    def test_report_contains_next_steps_section(self):
        run = _make_analysis_run()
        md = build_markdown_report(run)
        self.assertIn("## Recommended Next Steps", md)

    def test_next_steps_before_human_review_checklist(self):
        run = _make_analysis_run()
        md = build_markdown_report(run)
        next_steps_pos = md.index("## Recommended Next Steps")
        checklist_pos = md.index("## Human Review Checklist")
        self.assertLess(next_steps_pos, checklist_pos)

    def test_next_steps_with_warnings_contain_address_items(self):
        run = _make_analysis_run()
        vs = _make_validation_summary()
        md = build_markdown_report(run, validation_summary=vs)
        self.assertIn("Address", md)
        self.assertIn("Insufficient samples", md)


if __name__ == "__main__":
    unittest.main()
