"""Pure reporting logic for the generate_report MCP tool.

No MCP imports. No side effects. Just builds strings and dicts from contracts.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from chemometrics_contracts import (
        AnalysisRun,
        InterpretationSummary,
        ValidationSummary,
    )

_HUMAN_REVIEW_CHECKLIST = """\
## Human Review Checklist

- [ ] Confirm the label column matches the intended scientific question.
- [ ] Confirm the preprocessing method is appropriate for this spectral modality.
- [ ] Confirm the validation strategy prevents data leakage.
- [ ] Confirm key metrics are plausible (not suspiciously high).
- [ ] Review any validation warnings before accepting results.
- [ ] Confirm feature importance reflects model evidence, not chemical causality.
- [ ] Confirm final conclusions are not overstated."""

_FOOTER = "---\n*Report generated by agentic-chemometrician. All conclusions require human review.*"


def _severity_order(w: object) -> int:
    """Sort warnings by severity: error first, then warning, then info."""
    s = getattr(w, "severity", "warning")
    return {"error": 0, "warning": 1, "info": 2}.get(s, 1)


def build_markdown_report(
    run: "AnalysisRun",
    validation_summary: "ValidationSummary | None" = None,
    interpretation: "InterpretationSummary | None" = None,
) -> str:
    """Build a Markdown report string from analysis run data."""
    lines: list[str] = []

    # 1. Title
    lines.append("# Chemometrics Analysis Report")
    lines.append("")

    # 2. Run metadata
    lines.append("## Run Metadata")
    if run.run_metadata is not None:
        meta = run.run_metadata
        lines.append(f"- **Run ID:** {meta.run_id}")
        lines.append(f"- **Tool:** {meta.tool_name}")
        lines.append(f"- **Status:** {meta.status or 'unknown'}")
        lines.append(f"- **Created at:** {meta.created_at or 'unknown'}")
    else:
        lines.append("- **Run ID:** unknown")
        lines.append("- **Tool:** unknown")
        lines.append("- **Status:** unknown")
        lines.append("- **Created at:** unknown")
    lines.append("")

    # 3. Dataset summary
    lines.append("## Dataset Summary")
    task_name = None
    if run.results:
        task_name = run.results[0].task_name
    params = {}
    if run.run_metadata is not None and run.run_metadata.parameters:
        params = dict(run.run_metadata.parameters)
    n_samples = params.get("n_samples", "unknown")
    n_features = params.get("n_features", "unknown")
    lines.append(f"- **Task:** {task_name or 'unknown'}")
    lines.append(f"- **Samples:** {n_samples}")
    lines.append(f"- **Features:** {n_features}")
    lines.append("")

    # 4. Results table
    lines.append("## Results")
    if run.results:
        lines.append("| Model | Task | Preprocessing | Key Metric | Value |")
        lines.append("|-------|------|---------------|------------|-------|")
        for result in run.results:
            model = result.model_name
            task = result.task_name
            preprocessing = ", ".join(result.preprocessing) if result.preprocessing else "none"
            # Pick first float metric as key metric
            key_metric = ""
            key_value = ""
            for k, v in result.metrics.items():
                if isinstance(v, float):
                    key_metric = k
                    key_value = f"{v:.4f}"
                    break
            lines.append(f"| {model} | {task} | {preprocessing} | {key_metric} | {key_value} |")
    else:
        lines.append("*No results available.*")
    lines.append("")

    # 5. Failed models
    if run.failed_models:
        lines.append("## Failed Models")
        lines.append(
            "The following models failed and are excluded from comparison:"
        )
        for fm in run.failed_models:
            lines.append(f"- {fm}")
        lines.append("")

    # 6. Validation
    if validation_summary is not None:
        lines.append("## Validation")
        passed_str = "PASSED" if validation_summary.passed else "FAILED"
        if validation_summary.passed is None:
            passed_str = "UNKNOWN"
        lines.append(f"- **Result:** {passed_str}")
        if validation_summary.warnings:
            lines.append("")
            lines.append("**Validation warnings:**")
            sorted_warnings = sorted(validation_summary.warnings, key=_severity_order)
            for w in sorted_warnings:
                lines.append(f"- [{w.severity.upper()}] {w.message}")
        lines.append("")

    # 7. Interpretation
    if interpretation is not None:
        lines.append("## Interpretation")
        if interpretation.summary:
            lines.append(interpretation.summary)
            lines.append("")
        if interpretation.model_comparisons:
            lines.append("**Model comparisons:**")
            for comp in interpretation.model_comparisons:
                lines.append(f"- {comp}")
            lines.append("")

    # 8. Warnings
    all_warnings = list(run.warnings)
    if all_warnings:
        lines.append("## Warnings")
        sorted_warnings = sorted(all_warnings, key=_severity_order)
        current_severity = None
        for w in sorted_warnings:
            if w.severity != current_severity:
                current_severity = w.severity
                lines.append(f"**{w.severity.capitalize()}:**")
            lines.append(f"- {w.message}")
        lines.append("")

    # 9. Artifacts
    if run.artifacts:
        lines.append("## Artifacts")
        for art in run.artifacts:
            label = art.label or art.kind
            lines.append(f"- [{label}]({art.uri}) — *{art.kind}*")
        lines.append("")

    # 10. Human review checklist
    lines.append(_HUMAN_REVIEW_CHECKLIST)
    lines.append("")

    # 11. Footer
    lines.append(_FOOTER)

    return "\n".join(lines)


def build_agent_readable_summary(
    run: "AnalysisRun",
    validation_summary: "ValidationSummary | None" = None,
) -> dict:
    """Build a JSON-serializable dict summary for agent consumption."""
    run_id = "unknown"
    if run.run_metadata is not None:
        run_id = run.run_metadata.run_id

    models_run = [r.model_name for r in run.results]

    # Find best accuracy across results
    best_accuracy: float | None = None
    for result in run.results:
        for k, v in result.metrics.items():
            if "accuracy" in k.lower() and isinstance(v, (int, float)):
                val = float(v)
                if best_accuracy is None or val > best_accuracy:
                    best_accuracy = val

    validation_passed: bool | None = None
    if validation_summary is not None:
        validation_passed = validation_summary.passed

    n_warnings = len(run.warnings)

    return {
        "run_id": run_id,
        "n_results": len(run.results),
        "failed_models": list(run.failed_models),
        "n_warnings": n_warnings,
        "validation_passed": validation_passed,
        "best_accuracy": best_accuracy,
        "models_run": models_run,
        "approval_required": True,
    }
