"""Pure reporting logic for the generate_report MCP tool.

No MCP imports. No side effects. Just builds strings and dicts from contracts.
"""
from __future__ import annotations

import collections
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from chemometrics_contracts import (
        AnalysisResult,
        AnalysisRun,
        InterpretationSummary,
        ValidationSummary,
    )

from chemometrics_mcp.core.fallback import recommend_fallback

_HUMAN_REVIEW_CHECKLIST = """\
## Human Review Checklist

- [ ] Confirm the label column matches the intended scientific question.
- [ ] Confirm the preprocessing method is appropriate for this spectral modality.
- [ ] Confirm the validation strategy prevents data leakage.
- [ ] Confirm key metrics are plausible (not suspiciously high).
- [ ] Review any validation warnings before accepting results.
- [ ] Confirm feature importance reflects model evidence, not chemical causality.
- [ ] Confirm final conclusions are not overstated."""

_FOOTER = "---\n*Report generated by agentic-chemometrician. All conclusions require human review.*"


def _severity_order(w: object) -> int:
    """Sort warnings by severity: error first, then warning, then info."""
    s = getattr(w, "severity", "warning")
    return {"error": 0, "warning": 1, "info": 2}.get(s, 1)


def _build_next_steps(
    run: "AnalysisRun",
    validation_summary: "ValidationSummary | None",
    interpretation: "InterpretationSummary | None",
) -> list[str]:
    steps: list[str] = []

    if validation_summary is not None and validation_summary.warnings:
        for w in validation_summary.warnings:
            steps.append(f"Address {w.message} before accepting results")

    if run.failed_models:
        for fm in run.failed_models:
            fallback = recommend_fallback(fm, "unknown")
            if fallback is not None:
                steps.append(f"Consider running {fallback} as alternative to {fm}")
            else:
                steps.append(f"Investigate failure for {fm} — no automatic fallback available")

    preprocessing_methods: set[tuple[str, ...]] = set()
    if run.results:
        for result in run.results:
            preprocessing_methods.add(tuple(result.preprocessing))
    if len(preprocessing_methods) == 1:
        steps.append("Compare preprocessing methods to confirm robustness")

    has_split_stability = False
    if validation_summary is not None:
        has_split_stability = validation_summary.checks.get("split_stability", False)
    if not has_split_stability:
        steps.append("Run split instability analysis to confirm result stability")

    low_metric = False
    for result in run.results:
        for k, v in result.metrics.items():
            if isinstance(v, (int, float)):
                if "accuracy" in k.lower() and float(v) < 0.7:
                    low_metric = True
                if "r2" in k.lower() or "r²" in k.lower():
                    if float(v) < 0.5:
                        low_metric = True
    if low_metric:
        steps.append(
            "Consider additional preprocessing or feature selection to improve model performance"
        )

    if not steps:
        steps.append("Results are suitable for expert review and interpretation")

    return steps


def build_markdown_report(
    run: "AnalysisRun",
    validation_summary: "ValidationSummary | None" = None,
    interpretation: "InterpretationSummary | None" = None,
) -> str:
    """Build a Markdown report string from analysis run data."""
    lines: list[str] = []

    # 1. Title
    lines.append("# Chemometrics Analysis Report")
    lines.append("")

    # 2. Run metadata
    lines.append("## Run Metadata")
    if run.run_metadata is not None:
        meta = run.run_metadata
        lines.append(f"- **Run ID:** {meta.run_id}")
        lines.append(f"- **Tool:** {meta.tool_name}")
        lines.append(f"- **Status:** {meta.status or 'unknown'}")
        lines.append(f"- **Created at:** {meta.created_at or 'unknown'}")
    else:
        lines.append("- **Run ID:** unknown")
        lines.append("- **Tool:** unknown")
        lines.append("- **Status:** unknown")
        lines.append("- **Created at:** unknown")
    lines.append("")

    # 3. Dataset summary
    lines.append("## Dataset Summary")
    task_name = None
    if run.results:
        task_name = run.results[0].task_name
    params = {}
    if run.run_metadata is not None and run.run_metadata.parameters:
        params = dict(run.run_metadata.parameters)
    n_samples = params.get("n_samples", "unknown")
    n_features = params.get("n_features", "unknown")
    lines.append(f"- **Task:** {task_name or 'unknown'}")
    lines.append(f"- **Samples:** {n_samples}")
    lines.append(f"- **Features:** {n_features}")
    lines.append("")

    # 4. Preprocessing comparison (only when multiple preprocessing methods present)
    unique_preprocessings: set[str] = set()
    if run.results:
        for result in run.results:
            prep_str = ", ".join(result.preprocessing) if result.preprocessing else "none"
            unique_preprocessings.add(prep_str)

    if len(unique_preprocessings) > 1:
        lines.append("## Preprocessing Comparison")
        lines.append("| Preprocessing | Model | Metric | Value |")
        lines.append("|---------------|-------|--------|-------|")
        for result in run.results:
            prep_str = ", ".join(result.preprocessing) if result.preprocessing else "none"
            model = result.model_name
            key_metric = ""
            key_value = ""
            for k, v in result.metrics.items():
                if isinstance(v, float):
                    key_metric = k
                    key_value = f"{v:.4f}"
                    break
            lines.append(f"| {prep_str} | {model} | {key_metric} | {key_value} |")
        lines.append("")

    # 4b. Standalone model comparison table (always included)
    lines.append(build_model_comparison_table(list(run.results)))
    lines.append("")

    # 5. Results table
    lines.append("## Results")
    if run.results:
        lines.append("| Model | Task | Preprocessing | Key Metric | Value |")
        lines.append("|-------|------|---------------|------------|-------|")
        for result in run.results:
            model = result.model_name
            task = result.task_name
            preprocessing = ", ".join(result.preprocessing) if result.preprocessing else "none"
            # Pick first float metric as key metric
            key_metric = ""
            key_value = ""
            for k, v in result.metrics.items():
                if isinstance(v, float):
                    key_metric = k
                    key_value = f"{v:.4f}"
                    break
            lines.append(f"| {model} | {task} | {preprocessing} | {key_metric} | {key_value} |")
    else:
        lines.append("*No results available.*")
    lines.append("")

    # 5b. Cross-Modality Comparison
    _ftir_specific = {"baseline_correction", "area_normalization"}
    has_ftir_prep = False
    has_standard_only = False
    for result in run.results:
        prep_set = set(result.preprocessing)
        if prep_set & _ftir_specific:
            has_ftir_prep = True
        if prep_set and not (prep_set & _ftir_specific):
            has_standard_only = True

    cross_modality_detected = has_ftir_prep and has_standard_only
    if cross_modality_detected:
        lines.append("## Cross-Modality Comparison")
        lines.append(
            "Results from multiple spectral modalities appear to be present. "
            "The following caveats apply:"
        )
        lines.append("")
        lines.append(
            "- **Different preprocessing** may have been applied to each modality, "
            "making direct metric comparison misleading."
        )
        lines.append(
            "- **Different feature counts** across modalities mean that model "
            "complexity and performance are not directly comparable."
        )
        lines.append(
            "- **Model hyperparameters** were likely not tuned independently "
            "per modality."
        )
        lines.append(
            "- Cross-modality comparisons should be interpreted as exploratory "
            "only. Do not claim one modality is superior without controlled "
            "per-modality validation."
        )
        lines.append("")

    # 5. Failed models
    if run.failed_models:
        lines.append("## Failed Models")
        lines.append(
            "The following models failed and are excluded from comparison:"
        )
        for fm in run.failed_models:
            lines.append(f"- {fm}")
        lines.append("")

    # 6. Validation
    if validation_summary is not None:
        lines.append("## Validation")
        passed_str = "PASSED" if validation_summary.passed else "FAILED"
        if validation_summary.passed is None:
            passed_str = "UNKNOWN"
        lines.append(f"- **Result:** {passed_str}")
        if validation_summary.warnings:
            lines.append("")
            lines.append("**Validation warnings:**")
            sorted_warnings = sorted(validation_summary.warnings, key=_severity_order)
            for w in sorted_warnings:
                lines.append(f"- [{w.severity.upper()}] {w.message}")
        lines.append("")

    # 7. Interpretation
    if interpretation is not None:
        lines.append("## Interpretation")
        if interpretation.summary:
            lines.append(interpretation.summary)
            lines.append("")
        if interpretation.model_comparisons:
            lines.append("**Model comparisons:**")
            for comp in interpretation.model_comparisons:
                lines.append(f"- {comp}")
            lines.append("")

    # 8. Warnings
    all_warnings = list(run.warnings)
    if all_warnings:
        lines.append("## Warnings")
        sorted_warnings = sorted(all_warnings, key=_severity_order)
        current_severity = None
        for w in sorted_warnings:
            if w.severity != current_severity:
                current_severity = w.severity
                lines.append(f"**{w.severity.capitalize()}:**")
            lines.append(f"- {w.message}")
        lines.append("")

    # 9. Artifacts
    if run.artifacts:
        lines.append("## Artifacts")
        for art in run.artifacts:
            label = art.label or art.kind
            lines.append(f"- [{label}]({art.uri}) — *{art.kind}*")
        lines.append("")

    # 10. Recommended Next Steps
    next_steps = _build_next_steps(run, validation_summary, interpretation)
    lines.append("## Recommended Next Steps")
    for step in next_steps:
        lines.append(f"- {step}")
    lines.append("")

    # 11. Human review checklist
    lines.append(_HUMAN_REVIEW_CHECKLIST)
    lines.append("")

    # 12. Footer
    lines.append(_FOOTER)

    return "\n".join(lines)


_MODEL_COMPLEXITY: dict[str, str] = {
    "svm_rbf": "medium (kernel SVM, O(n²) fit)",
    "svr": "medium (kernel SVR, O(n²) fit)",
    "random_forest": "medium (100 trees)",
    "random_forest_reg": "medium (100 trees)",
    "pca_lda": "low (linear)",
    "logistic_regression": "low (linear, L2)",
    "ridge": "low (linear, L2)",
    "plsr": "low (latent variable)",
    "pca": "low (linear)",
    "kmeans": "low",
    "xgboost": "high (gradient boosting)",
    "xgboost_reg": "high (gradient boosting)",
}


def build_model_comparison_table(
    results: "list[AnalysisResult] | tuple[AnalysisResult, ...]",
) -> str:
    """Build a standalone Markdown model-comparison table.

    Columns: Task | Model | Key metric | Value | Complexity | CV-std (stability).

    ``CV-std`` is the standard deviation of the primary metric across multiple
    seeds if more than one result exists for the same model; otherwise ``n/a``.

    Parameters
    ----------
    results:
        Sequence of :class:`AnalysisResult` objects to compare.

    Returns
    -------
    str
        Markdown table as a string.
    """
    if not results:
        return "*No results available for comparison.*"

    # Group results by (task_name, model_name) to compute CV-std across seeds
    grouped: dict[tuple[str, str], list["AnalysisResult"]] = collections.defaultdict(list)
    for r in results:
        grouped[(r.task_name, r.model_name)].append(r)

    lines: list[str] = [
        "## Model Comparison Table",
        "",
        "| Task | Model | Key Metric | Value | Complexity | Stability (CV-std) |",
        "|------|-------|------------|-------|------------|--------------------|",
    ]

    # Determine primary metric per task type
    def _primary_metric(r: "AnalysisResult") -> tuple[str, float | None]:
        if "classification" in r.task_name:
            for k in ("accuracy", "balanced_accuracy", "f1_weighted", "f1_macro"):
                if k in r.metrics and isinstance(r.metrics[k], (int, float)):
                    return k, float(r.metrics[k])
        elif "regression" in r.task_name:
            for k in ("r2", "rmse", "mae"):
                if k in r.metrics and isinstance(r.metrics[k], (int, float)):
                    return k, float(r.metrics[k])
        # fallback: first numeric metric
        for k, v in r.metrics.items():
            if isinstance(v, (int, float)):
                return k, float(v)
        return "—", None

    seen: set[tuple[str, str]] = set()
    for (task, model), group in grouped.items():
        if (task, model) in seen:
            continue
        seen.add((task, model))

        # Representative result (last one, as it may reflect best preprocessing)
        rep = group[-1]
        metric_key, metric_val = _primary_metric(rep)
        val_str = f"{metric_val:.4f}" if metric_val is not None else "—"

        complexity = _MODEL_COMPLEXITY.get(model, "unknown")

        # Stability: std across seeds/runs if more than one result
        if len(group) > 1:
            vals = [_primary_metric(r)[1] for r in group if _primary_metric(r)[1] is not None]
            if len(vals) > 1:
                cv_std = float(np.std(vals, ddof=0))
                stability_str = f"{cv_std:.4f}"
            else:
                stability_str = "n/a"
        else:
            stability_str = "n/a"

        lines.append(
            f"| {task} | {model} | {metric_key} | {val_str} | {complexity} | {stability_str} |"
        )

    lines.append("")
    lines.append(
        "*Stability = std of primary metric across seeds (lower is better). "
        "n/a = single run only.*"
    )
    return "\n".join(lines)


def build_agent_readable_summary(
    run: "AnalysisRun",
    validation_summary: "ValidationSummary | None" = None,
) -> dict:
    """Build a JSON-serializable dict summary for agent consumption."""
    run_id = "unknown"
    if run.run_metadata is not None:
        run_id = run.run_metadata.run_id

    models_run = [r.model_name for r in run.results]

    # Find best accuracy across results
    best_accuracy: float | None = None
    for result in run.results:
        for k, v in result.metrics.items():
            if "accuracy" in k.lower() and isinstance(v, (int, float)):
                val = float(v)
                if best_accuracy is None or val > best_accuracy:
                    best_accuracy = val

    validation_passed: bool | None = None
    if validation_summary is not None:
        validation_passed = validation_summary.passed

    n_warnings = len(run.warnings)

    return {
        "run_id": run_id,
        "n_results": len(run.results),
        "failed_models": list(run.failed_models),
        "n_warnings": n_warnings,
        "validation_passed": validation_passed,
        "best_accuracy": best_accuracy,
        "models_run": models_run,
        "approval_required": True,
    }
